mode: debug
mysql:
  dsn: >-
    ${MYSQL_USERNAME}:${MYSQL_PASSWORD}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/zeus?charset=utf8&parseTime=True&loc=Local
  pool:
    min: 5
    max: 20
jwt:
  key:
    private: /keys/jwt_private_key.pem
    public: /keys/jwt_public_key.pem