mode: debug
mysql:
  dsn: >-
    ${MYSQL_USERNAME}:${MYSQL_PASSWORD}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/${MYSQL_DB}?charset=utf8&parseTime=True&loc=Local
  pool:
    min: 5
    max: 20
redis:
  host: 127.0.0.1:6379
  auth:
jwt:
  key:
    private: keys/jwt_private_key.pem
    public: keys/jwt_public_key.pem
lang:
  types: zh-CN|en-US
  names: 简体中文|English
domain: bullteam.local
