casbin:
  model:
    rule_0: config/casbin/rbac_model_0.conf
cors:
  allow_credentials: false
  allow_headers:
  - '*'
  allow_methods:
  - GET
  - POST
  - OPTIONS
  - PUT
  - DELETE
  allow_origins:
  - '*'
  enable: false
  max_age: 7200
dingtalk:
  snsappid: dingoa1uudyxl2dcjvqpij
  snssecret: o8YvDT5l2zb9dikuCbz0HXOiOaVwdyVResrDVyFaqojv0EwZp8ygAemFyoSBh_lz
domain: bullteam.local
email:
  from: xxxxxx@qq.com
  host: smtp.qq.com
  password: xxxxxxxx
  port: 25
  username: xxx@qq.com
jwt:
  expiresat: 3600*24*1
  key:
    private: keys/jwt_private_key.pem
    public: keys/jwt_public_key.pem
lang:
  names: 简体中文|English
  types: zh-CN|en-US
ldap:
  addr: 127.0.0.1:389
  attributes:
  - cn
  - displayName
  - mail
  authfilter: (&(uid=%s))
  basedn: dc=bullteam,dc=com
  binddn: cn=admin,dc=bullteam,dc=com
  bindpass: zeus@admin#123456
  starttls: false
  tls: false
  userdn: cn=admin,dc=bullteam,dc=com
mode: debug
mysql:
  dsn: root:123456@tcp(127.0.0.1:3306)/zeus?charset=utf8&parseTime=True&loc=Local
  pool:
    max: 20
    min: 5
redis:
  host: 127.0.0.1:6379
  pool:
    max: 20
    min: 3
test:
  test: "1111"
