base:
  baseurl: http://localhost:8082/
  logpath: /data/log
  port: 8082
  sitename: Zeus 宙斯权限后台管理系统
casbin:
  model:
    rule_0: config/casbin/rbac_model_0.conf
cors:
  allow_credentials: false
  allow_headers:
  - '*'
  allow_methods:
  - GET
  - POST
  - OPTIONS
  - PUT
  - DELETE
  allow_origins:
  - '*'
  enable: false
  max_age: 7200
database:
  driver: sqlite
  mysql:
    dsn: root:root@tcp(127.0.0.1:3306)/auth?charset=utf8&parseTime=True&loc=Local
    pool:
      max: 20
      min: 5
  sqlite:
    dsn: data/zeus.db
dingtalk:
  snsappid: dingoa1uudyxl2dcjvqpij
  snssecret: o8YvDT5l2zb9dikuCbz0HXOiOaVwdyVResrDVyFaqojv0EwZp8ygAemFyoSBh_lz
domain: bullteam.local
email:
  port: 25
  smtpaddress: xxxxxx@qq.com
  smtppassword: xxxxxxxx
  smtpserver: smtp.qq.com
  smtpuser: xxx@qq.com
jwt:
  expiresat: 3600*24*1
  key:
    private: keys/jwt_private_key.pem
    public: keys/jwt_public_key.pem
lang:
  names: 简体中文|English
  types: zh-CN|en-US
ldap:
  addr: 127.0.0.1:389
  attributes:
  - cn
  - displayName
  - mail
  authfilter: (&(uid=%s))
  basedn: dc=bullteam,dc=com
  binddn: cn=admin,dc=bullteam,dc=com
  bindpass: zeus@admin#123456
  starttls: false
  tls: false
  userdn: cn=admin,dc=bullteam,dc=com
mode: debug
redis:
  host: 127.0.0.1:6379
  pool:
    max: 20
    min: 3
project:
  merge: true
security:
  install_lock: true
