mode="debug"
[logger]
    [logger.console]
        color=true
        prefix="[zeus]"
        level="Debug"
    [logger.zap]
        path="zeus.log"
        level="Debug"
[mysql]
    dsn="${MYSQL_USERNAME}:${MYSQL_PASSWORD}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/zeus?charset=utf8&parseTime=True&loc=Local"
    [pool]
        min=5
        max=20