basePath: /v1
definitions:
  model.User:
    properties:
      created_time:
        example: 2019-07-10 0:39
        type: string
      department_id:
        example: 1
        type: integer
      email:
        example: xxxx@hotmail.com
        type: string
      faceicon:
        example: http://xxx.com
        type: string
      id:
        example: 1
        type: integer
      mobile:
        example: "186000000"
        type: string
      realname:
        example: 黄梧桐
        type: string
      sex:
        example: 1
        type: integer
      status:
        example: 1
        type: integer
      title:
        example: title
        type: string
      updated_time:
        example: 2019-07-10 0:39
        type: string
      username:
        example: wutongci
        type: string
    type: object
host: 127.0.0.1:8012
info:
  contact:
    email: support@bullteam.cn
    name: API Support
  description: Zeus 宙斯权限后台
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Zeus 宙斯权限后台 API
  version: V0.1
paths:
  /account/EmailVerification:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"result":[]}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 验证邮件地址(验证)
      tags:
      - account
  /account/ThirdUnbind:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"result":[]}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 解除绑定第三方应用
      tags:
      - account
  /account/Thirdbind:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"result":[]}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 解除绑定第三方应用
      tags:
      - account
  /account/accountinfo:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"result":[]}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 获取个人中心用户信息
      tags:
      - account
  /account/bindcode:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"result":[]}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 绑定2fa goole 验证码
      tags:
      - account
  /account/domains:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"result":[]}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 获取用户管理域
      tags:
      - account
  /account/info:
    get:
      consumes:
      - application/json
      description: 登陆用户信息接口
      parameters:
      - description: 用户ID
        in: path
        name: userId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"id":1,"name":"wutong"}}'
          schema:
            items:
              $ref: '#/definitions/model.User'
            type: array
      security:
      - ApiKeyAuth: []
      summary: 登录用户信息
      tags:
      - account
  /account/password:
    put:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"id":1}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 更新个人密码
      tags:
      - account
  /account/third:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"result":[]}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 验证邮件地址(发送邮件)
      tags:
      - account
  /datas:
    get:
      parameters:
      - description: 条数
        in: query
        name: limit
        type: integer
      - description: 偏移量
        in: query
        name: skip
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"result":[...],"total":1}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 数据权限列表[分页+搜索]
      tags:
      - DataPerm
    post:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"id":1}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 新增数据权限
      tags:
      - DataPerm
  /datas/{id}:
    delete:
      parameters:
      - description: 要删除的id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"id":1}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 删除项目
      tags:
      - DataPerm
    get:
      parameters:
      - description: 数据权限id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"id":1,"name":"test"}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 数据权限详情
      tags:
      - DataPerm
    put:
      parameters:
      - description: 需要编辑的id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"id":1}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 编辑数据权限
      tags:
      - DataPerm
  /depts:
    get:
      parameters:
      - description: 条数
        in: query
        name: limit
        type: integer
      - description: 偏移量
        in: query
        name: skip
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"result":[...],"total":1}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 部门列表[分页+搜索]
      tags:
      - Department
    post:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"id":1}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 新增部门
      tags:
      - Department
  /depts/{id}:
    delete:
      parameters:
      - description: 部门id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"id":1}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 删除部门
      tags:
      - Department
    get:
      parameters:
      - description: 部门id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"id":1,"name":"test"}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 部门信息
      tags:
      - Department
    put:
      parameters:
      - description: 部门id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"id":1}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 编辑部门
      tags:
      - Department
  /domains:
    get:
      parameters:
      - description: 条数
        in: query
        name: limit
        type: integer
      - description: 偏移量
        in: query
        name: skip
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"result":[...],"total":1}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 项目列表[分页+搜索]
      tags:
      - Domain
    post:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"id":1}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 新增项目
      tags:
      - Domain
  /domains/{id}:
    delete:
      parameters:
      - description: 项目id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"id":1}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 删除项目
      tags:
      - Domain
    get:
      parameters:
      - description: 项目id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"id":1,"name":"test"}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 项目信息
      tags:
      - Domain
    put:
      parameters:
      - description: 项目id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"id":1}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 编辑项目
      tags:
      - Domain
  /healthcheck:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{""}}'
          schema:
            type: string
      summary: 健康检查
      tags:
      - Health
  /log/login:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"id":1,"name":"test"}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 登录日志列表
      tags:
      - Log
  /log/login/{logId}:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"id":1,"name":"test"}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 登录日志信息
      tags:
      - Log
  /log/operation:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"id":1,"name":"test"}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 操作日志信息
      tags:
      - Log
  /log/operation/{logId}:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"id":1,"name":"test"}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 操作日志列表
      tags:
      - Log
  /menus:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"result":[...],"total":1}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 菜单列表
      tags:
      - menu
    post:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"id":1}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 新增菜单
      tags:
      - menu
  /menus/:
    delete:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"id":1}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 删除菜单
      tags:
      - menu
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"id":1,"name":"wutong"}}'
          schema:
            items:
              $ref: '#/definitions/model.User'
            type: array
        "400":
          description: '{"code":10004,"msg": "用户信息不存在"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 菜单信息
      tags:
      - menu
    put:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"id":1}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 编辑菜单
      tags:
      - menu
  /roles:
    get:
      parameters:
      - description: 条数
        in: query
        name: limit
        type: integer
      - description: 偏移量
        in: query
        name: skip
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"result":[...],"total":1}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 角色列表[分页+搜索]
      tags:
      - Role
    post:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"id":1}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 新增角色
      tags:
      - Role
  /roles/:
    delete:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"result":[...],"total":1}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 删除角色信息
      tags:
      - Role
    put:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"result":[...],"total":1}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 更新角色信息
      tags:
      - Role
  /roles/{id}:
    get:
      parameters:
      - description: 角色id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"id":1,"name":"test"}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 角色信息
      tags:
      - Role
  /users:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"id":1}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 新增用户
      tags:
      - Users
  /users/{id}:
    delete:
      parameters:
      - description: 用户id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"id":1}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 删除用户
      tags:
      - Users
    get:
      consumes:
      - application/json
      parameters:
      - description: 用户id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"id":1,"name":"wutong"}}'
          schema:
            items:
              $ref: '#/definitions/model.User'
            type: array
        "400":
          description: '{"code":10004,"msg": "用户信息不存在"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 用户信息
      tags:
      - Users
    put:
      parameters:
      - description: 用户id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"id":1}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 编辑用户
      tags:
      - Users
  /users/{id}/password:
    put:
      parameters:
      - description: 用户id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"id":1}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 更新用户密码
      tags:
      - Users
  /users/{id}/permissions:
    get:
      parameters:
      - description: 用户id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"id":1}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 获取用户权限列表
      tags:
      - Users
  /users/{id}/status:
    put:
      parameters:
      - description: 用户id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"id":1}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 更新用户状态
      tags:
      - Users
  /users/department/move:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"id":1}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 移动部门
      tags:
      - Users
  /users/login:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: 登录名
        in: formData
        name: username
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      - description: 验证码ID
        in: formData
        name: captchaid
        type: string
      - description: 验证码
        in: formData
        name: captchaval
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"id":1,"name":"wutong"}}'
          schema:
            type: string
        "400":
          description: '{"code":10004,"msg": "用户信息不存在"}'
          schema:
            type: string
      summary: 用户登录
      tags:
      - Users
  /users/login/refresh:
    post:
      consumes:
      - multipart/form-data
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"data":{"id":1,"name":"wutong"}}'
          schema:
            type: string
        "400":
          description: '{"code":10004,"msg": "用户信息不存在"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 刷新token
      tags:
      - Users
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
